service: courtsearch

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  timeout: 15
  logRetentionInDays: 3

functions:
  courtsearch:
    handler: handler.courtsearch
    events:
      - http:
          path: /search
          method: post
          cors: true